### ISSUE TITLE
About Data

### ISSUE THREAD

**Issue by 1q84er** [QizhiPei/SMT-DTA#4]
Hello QizhiPei,
It's an interesting job!
Could you please tell me how to generate the train.mol file and train.pro file while preprocessing the unlabeled data?
Thank you for your time!

**Comment by QizhiPei** [comment]
Hello 1q84er
@1q84er 
For the unlabeld molecule data(train.mol, valid.mol), you can randomly sample the SMILES from the [PubChem CID-SMILES file](https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/Extras/CID-SMILES.gz). Or you can extract and randomly sample the SMILES from the .sdf file from [PubChem ftp SDF](https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/). More details about the PubChem data can be found at [PubChem downloads](https://pubchemdocs.ncbi.nlm.nih.gov/downloads).
For the unlabeled protein data(train.pro. valid.mol), you can randomly sample the fasta from the Pfam [pfamseq.gz file](http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/pfamseq.gz). More details about the Pfam data can be found at [Pfam ftp site](https://pfam-docs.readthedocs.io/en/latest/ftp-site.html).
Note that more unlabeled data may improve the experiment results and the difference caused by randomness is not so important because of the huge size of the unlabled data
